### ISSUE TITLE
Screenshots do not show in ExtentHtml and a lot unnecessary steps.

### ISSUE THREAD

**Issue by mohamadsyauqi** [extent-framework/extentreports-cucumber4-adapter#20]
The embed screenshots do not show in ExtentHtml and like I stated in #10 , version 1.0.7 still add every hooks in the report.
Example: 
```
Logger.before(Scenario)
ContextSteps.beforeStep()
Given login to Dash
ContextSteps.AfterStep(Scenario)
ContextSteps.failedScenarioScreenshotCucumberHtml(Scenario)
```
Currently I am using v1.0.5 with additional enhancement like we discussed in #7 and it works great but I have to put a jar file into the repo.

**Comment by foursyth** [comment]
Hmm, as per this the hooks will only be included if they have meaningful content and the desired status.. 

[source.l205](https://github.com/extent-framework/extentreports-cucumber4-adapter/blob/master/src/main/java/com/aventstack/extentreports/cucumber/adapter/ExtentCucumberAdapter.java#L205)

Feel free to modify and send in a pull request if this is not ideal.

**Comment by sureshmanik** [comment]
> Hmm, as per this the hooks will only be included if they have meaningful content and the desired status..
> 
> [source.l205](https://github.com/extent-framework/extentreports-cucumber4-adapter/blob/master/src/main/java/com/aventstack/extentreports/cucumber/adapter/ExtentCucumberAdapter.java#L205)
> 
> Feel free to modify and send in a pull request if this is not ideal.

I am having the same problems in my code/project. Is there any fixes done on these issues?

**Comment by sureshmanik** [comment]
@foursyth I have fixed this issue in my local. can i send in a pull request.?

**Comment by kathyrollo** [comment]
Hi @foursyth 

Can confirm screenshots are not embedded in the HtmlReport in `1.0.6` onwards with boilerplate-looking hooks:
![html_reports_106](https://user-images.githubusercontent.com/28589393/59961208-212f1c00-9518-11e9-8768-8829c95980f8.png)

HtmlReport has embedded screenshots and is more human-readable using `1.0.5`. To provide context, HtmlReport is also business-facing; stakeholders do not need to see the intricacies of execution. The LoggerReport can do well for that.
![html_reports_105](https://user-images.githubusercontent.com/28589393/59961390-6eac8880-951a-11e9-9490-503bdde616aa.png)

Let me know if you need further testing. Thanks!

**Comment by Andyclark97** [comment]
Any news on this?

**Comment by anshooarora** [comment]
@sureshmanik Kindly send in the pull request, thank you

**Comment by kathyrollo** [comment]
Hi all, can confirm issue is still present in version `1.0.10` with Cucumber `4.8.1`. Have not updated since `1.0.5` with Cucumber `4.2.0` - the last working combination.

Guess @sureshmanik did not get the PR through. Whenever I present, the screenshots are a major selling point to stakeholders.

**Comment by anshooarora** [comment]
Its hard to tell where this broke looking at the revision history but I will check this over the weekend and provide a fix.

**Comment by anshooarora** [comment]
**Screenshots:**

Starting `1.0.11-SNAPSHOT`, you can use the `screenshot.rel.path` configuration in `extent.properties` to specify a relative path to be used in the report.  

Below is an example of the complete [extent.properties](https://github.com/extent-framework/extentreports-cucumber4-adapter/blob/master/config/extent.properties):

```
extent.reporter.avent.start=false
extent.reporter.bdd.start=false
extent.reporter.cards.start=false
extent.reporter.email.start=false
extent.reporter.html.start=false
extent.reporter.klov.start=false
extent.reporter.logger.start=false
extent.reporter.spark.start=true
extent.reporter.tabular.start=false

extent.reporter.avent.config=
extent.reporter.bdd.config=
extent.reporter.cards.config=
extent.reporter.email.config=
extent.reporter.html.config=
extent.reporter.klov.config=src/test/resources/klov.properties
extent.reporter.logger.config=
extent.reporter.spark.config=
extent.reporter.tabular.config=

extent.reporter.avent.out=test-output/AventReport/
extent.reporter.bdd.out=test-output/BddReport/
extent.reporter.cards.out=test-output/CardsReport/
extent.reporter.email.out=test-output/EmailReport/ExtentEmail.html
extent.reporter.html.out=test-output/HtmlReport/ExtentHtml.html
extent.reporter.logger.out=test-output/LoggerReport/
extent.reporter.spark.out=test-output/SparkReport/
extent.reporter.tabular.out=test-output/TabularReport/

screenshot.dir=test-output/
screenshot.rel.path=
```

So considering the below folder structure:

```
.
root
+-- src
+-- target
+-- test-output
    +-- spark/
        +-- index.html
    +-- embedded1.png
    +-- embedded2.png
```

Your relative path would be:

```
screenshot.rel.path=../
```

This version also uses the latest ExtentReports `4.1.2` which enables a SPA view for SparkReporter just like HtmlReporter.

**Comment by anshooarora** [comment]
The above commit now removes the extra steps appearing in the report:  the block to create node for each hook is now removed.  The screenshots will be attached to the immediately executed step before the embed event is called.

**Comment by anshooarora** [comment]
Please test using:

```
<groupId>com.aventstack</groupId>
<artifactId>extentreports-cucumber4-adapter</artifactId>
<version>1.0.11-SNAPSHOT</version>
```

**Comment by kathyrollo** [comment]
Hi @anshooarora ,
Thanks for looking into this.

Used below in my pom.xml:
```
<dependency>
	<groupId>io.cucumber</groupId>
	<artifactId>cucumber-junit</artifactId>
	<version>4.8.1</version>
</dependency>

<dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports-cucumber4-adapter</artifactId>
            <version>1.0.11-SNAPSHOT</version>
        </dependency>
```

Error:
```
[ERROR] Failed to execute goal on project : Could not resolve dependencies for project : Could not find artifact com.aventstack:extentreports-cucumber4-adapter:jar:1.0.11-SNAPSHOT -> [Help 1]
```

**Comment by anshooarora** [comment]
@kathyrollo You may not have snapshots enabled. Please see [here](https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository).

**Comment by kathyrollo** [comment]
Hi @anshooarora ,

Was able to download the `1.0.11-SNAPSHOT` and update to Cucumber `4.8.1`. A bunch of stuff got deprecated due to the move to `io.cucumber` pkg. Something is null and the tests are not starting even though I have updated all the imports. 

Will create a skeleton project to make things easier to investigate as my actual project is big. Be back soon as I have it.

**Comment by anshooarora** [comment]
@kathyrollo The current snapshot supports Cucumber version `4.7.4`.  There are a few breaking changes in 4.8.x, so supporting this version may not be feasible as version 5.x is now available.

**Comment by kathyrollo** [comment]
@anshooarora Do you have a skeleton project with Cucumber `4.74`? Could be easier to check what's wrong with mine using a working sample. :)

**Comment by kathyrollo** [comment]
Hi @anshooarora ,

Used Cucumber `4.7.4` with `1.0.11-SNAPSHOT`:
```
@RunWith(Cucumber.class)
@CucumberOptions(features = { "src/main/resources/features" }, glue = { "steps" }, tags = { "not @ignore" }, plugin = {
        "pretty", "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",
        "html:target/cucumber-html-default", "json:target/cucumber-report.json",
        "junit:target/cucumber-report.xml" }, strict = true, monochrome = true)
```
Output:
```
[ERROR] main.RunCukesTest  Time elapsed: 17.317 s  <<< ERROR!
cucumber.runtime.CucumberException: java.lang.NullPointerException
Caused by: java.lang.NullPointerException

[INFO] 
[INFO] Results:
[INFO]
[ERROR] Errors: 
[ERROR]   null
[ERROR]   RunCukesTest » Cucumber java.lang.NullPointerException
```
As an experiment, I removed the plugin
```
"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"
```
from `@CucumberOptions` to check if the Cucumber update broke the tests.

Output:

The tests ran and passed. It also generated the far less pretty default HTML report with screenshots.

![default_cukes_html_reporter](https://user-images.githubusercontent.com/28589393/73729321-e917d900-4788-11ea-859a-349c341a7254.PNG)

Is there anything missed with the plugin declaration?

**Comment by anshooarora** [comment]
I suspect the NPE is due to the `screenshot.rel.path` ([src](https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/20#issuecomment-581305340)) entry not present in `extent.properties`?   I have accounted for this and pushed the latest snapshot,  please try again.

**Comment by kathyrollo** [comment]
Hi @anshooarora ,

Still getting null:
```
extent.reporter.avent.start=false
extent.reporter.bdd.start=false
extent.reporter.cards.start=false
extent.reporter.email.start=false
extent.reporter.html.start=false
extent.reporter.klov.start=false
extent.reporter.logger.start=false
extent.reporter.spark.start=true
extent.reporter.tabular.start=false

extent.reporter.avent.config=
extent.reporter.bdd.config=
extent.reporter.cards.config=
extent.reporter.email.config=
extent.reporter.html.config=
extent.reporter.klov.config=
extent.reporter.logger.config=
extent.reporter.spark.config=
extent.reporter.tabular.config=

extent.reporter.avent.out=test-output/AventReport/
extent.reporter.bdd.out=test-output/BddReport/
extent.reporter.cards.out=test-output/CardsReport/
extent.reporter.email.out=test-output/EmailReport/ExtentEmail.html
extent.reporter.html.out=test-output/HtmlReport/ExtentHtml.html
extent.reporter.logger.out=test-output/LoggerReport/
extent.reporter.spark.out=test-output/SparkReport/
extent.reporter.tabular.out=test-output/TabularReport/

screenshot.dir=test-output/
screenshot.rel.path=../
```
klov is blank because I do not have klov config.

**Comment by anshooarora** [comment]
@kathyrollo  I made a few more fixes,  please do a force refresh and try again.  If you are still getting a NPE,  can you share a snippet that I can use to reproduce this?

**Comment by kathyrollo** [comment]
Hi @anshooarora ,

Here are the results of my snapshot testing:

### Snippets
```
// pom.xml
<dependency>
	<groupId>io.cucumber</groupId>
	<artifactId>cucumber-junit</artifactId>
	<version>4.7.4</version>
</dependency>
<dependency>
	<groupId>io.cucumber</groupId>
	<artifactId>cucumber-picocontainer</artifactId>
	<version>4.7.4</version>
</dependency>
<dependency>
	<groupId>com.aventstack</groupId>
	<artifactId>extentreports-cucumber4-adapter</artifactId>
	<version>1.0.11-SNAPSHOT</version>
</dependency>



// RunCukesTest.java
import io.cucumber.core.cli.Main;
import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;

@RunWith(Cucumber.class)
@CucumberOptions(features = { "src/main/resources/features" }, glue = { "steps" }, tags = { "not @ignore" }, plugin = {
        "pretty", "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",
        "html:target/test-output/default-reports", "json:target/test-output/results.json",
        "junit:target/test-output/results.xml" }, strict = true, monochrome = true)
public class RunCukesTest {}



// extent.properties
extent.reporter.avent.start=false
extent.reporter.bdd.start=false
extent.reporter.cards.start=false
extent.reporter.email.start=false
extent.reporter.html.start=false
extent.reporter.klov.start=false
extent.reporter.logger.start=false
extent.reporter.spark.start=true
extent.reporter.tabular.start=false

extent.reporter.avent.config=
extent.reporter.bdd.config=
extent.reporter.cards.config=
extent.reporter.email.config=
extent.reporter.html.config=
extent.reporter.klov.config=
extent.reporter.logger.config=
extent.reporter.spark.config=
extent.reporter.tabular.config=

extent.reporter.avent.out=target/test-output/extent-reports/AventReport/
extent.reporter.bdd.out=target/test-output/extent-reports/BddReport/
extent.reporter.cards.out=target/test-output/extent-reports/CardsReport/
extent.reporter.email.out=target/test-output/extent-reports/EmailReport/ExtentEmail.html
extent.reporter.html.out=target/test-output/extent-reports/HtmlReport/ExtentHtml.html
extent.reporter.logger.out=target/test-output/extent-reports/LoggerReport/
extent.reporter.spark.out=target/test-output/extent-reports/SparkReport/
extent.reporter.tabular.out=target/test-output/extent-reports/TabularReport/

screenshot.dir=target/test-output/extent-reports/
screenshot.rel.path=../



// @AfterStep hook
@AfterStep
public void capture(Scenario scenario) {
	byte[] imgBytes = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
	scenario.embed(imgBytes, "image/png");
}
```

mvn:
```
mvn clean verify -U -Dcucumber.options="--tags @quickRun"
```
`-U` to force the snapshot update.

### Actual Result: 1.0.11-SNAPSHOT

The test did not execute and NPE is thrown. The generated SparkReport is empty with a false pass.

```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 12.903 s <<< FAILURE! - in main.RunCukesTest
[ERROR] Feature: Search  Time elapsed: 11.218 s  <<< ERROR!
java.lang.NullPointerException

[ERROR] main.RunCukesTest  Time elapsed: 11.735 s  <<< ERROR!
cucumber.runtime.CucumberException: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
```

![er_1 0 11-SNAPSHOT](https://user-images.githubusercontent.com/28589393/74390846-898b8e80-4e56-11ea-8927-9259b3578d5c.PNG)

### Actual Result: 1.0.10

For comparison, I downgraded the adapter to `1.0.10` while keeping everything else the same. The test executes and no NPE is thrown. The generated SparkReport throws the expected failure (the application under test has failed) but there are no embedded screenshots and the hook steps are visible (the defect we are trying to fix in `1.0.11`).

![er_1 0 10](https://user-images.githubusercontent.com/28589393/74393984-a7a9bc80-4e5f-11ea-9b3b-5c287b4805a0.PNG)

Let me know if there are other details you may need. Cheers!

**Comment by salunkhe-ravi** [comment]
Any update on this?
I'm unable to see embedded snapshots in the report!

**Comment by salunkhe-ravi** [comment]
This is what I'm getting with cucumber 4.7.4 and the 1-0.11-SNAPSHOT maven:

Mar 20, 2020 5:16:15 AM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> config.getConfig("js")  [in template "commons/commons-inject-js.ftl" at line 2, column 3]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${config.getConfig("js")}  [in template "commons/commons-inject-js.ftl" at line 2, column 1]
	- Reached through: #include "../commons/commons-inject-j...  [in template "logger/logger-test.ftl" at line 166, column 17]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:340)
	at freemarker.core.Environment.include(Environment.java:2925)
	at freemarker.core.Include.accept(Include.java:171)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:340)
	at freemarker.core.Environment.visit(Environment.java:340)
	at freemarker.core.Environment.process(Environment.java:313)
	at freemarker.template.Template.process(Template.java:383)
	at com.aventstack.extentreports.templating.FreemarkerTemplate.processTemplate(FreemarkerTemplate.java:53)
	at com.aventstack.extentreports.templating.FreemarkerTemplate.getSource(FreemarkerTemplate.java:40)
	at com.aventstack.extentreports.templating.FreemarkerTemplate.writeTemplate(FreemarkerTemplate.java:46)
	at com.aventstack.extentreports.reporter.BasicFileReporter.processTemplate(BasicFileReporter.java:152)
	at com.aventstack.extentreports.reporter.ExtentLoggerReporter.flush(ExtentLoggerReporter.java:59)
	at com.aventstack.extentreports.ReportObservable.lambda$23(ReportObservable.java:526)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.aventstack.extentreports.ReportObservable.notifyReporters(ReportObservable.java:526)
	at com.aventstack.extentreports.ReportObservable.flush(ReportObservable.java:424)
	at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:290)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.finishReport(ExtentCucumberAdapter.java:270)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.access$6(ExtentCucumberAdapter.java:269)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter$8.receive(ExtentCucumberAdapter.java:126)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter$8.receive(ExtentCucumberAdapter.java:1)
	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:45)
	at cucumber.runner.AbstractEventBus.send(AbstractEventBus.java:9)
	at cucumber.runner.TimeServiceEventBus.send(TimeServiceEventBus.java:3)
	at io.cucumber.testng.TestNGCucumberRunner.finish(TestNGCucumberRunner.java:88)
	at io.cucumber.testng.AbstractTestNGCucumberTests.tearDownClass(AbstractTestNGCucumberTests.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)

Mar 20, 2020 5:16:15 AM com.aventstack.extentreports.reporter.ExtentLoggerReporter flush
SEVERE: An exception occurred
FreeMarker template error:
The following has evaluated to null or missing:
==> config.getConfig("js")  [in template "commons/commons-inject-js.ftl" at line 2, column 3]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${config.getConfig("js")}  [in template "commons/commons-inject-js.ftl" at line 2, column 1]
	- Reached through: #include "../commons/commons-inject-j...  [in template "logger/logger-test.ftl" at line 166, column 17]

**Comment by anshooarora** [comment]
@salunkhe-ravi Looking into this. Can you share your instantiation code?

I have also pushed an updated snapshot, please do a force refresh (ensure SNAPSHOTS are also getting refreshed) and try again.

**Comment by salunkhe-ravi** [comment]
Hi @anshooarora still no luck

See my repo here pls:

https://github.com/salunkhe-ravi/Selenix/tree/master/Selenix

**Comment by anshooarora** [comment]
Fixed issue, please reimport/refresh pom.xml and try again.

**Comment by anshooarora** [comment]
@kathyrollo Also fixed the NPE, please check the latest [snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports-cucumber4-adapter/1.0.11-SNAPSHOT/).

**Comment by salunkhe-ravi** [comment]
Hello,

Nope no luck!

![image](https://user-images.githubusercontent.com/24796056/77145826-96cc1680-6aaf-11ea-93f0-3c908a182746.png)


Also, tried to revisit the imports from cucumbe.api to io.cucumber...but the issue still persists...

Updated the repo..pls check :(

**Comment by anshooarora** [comment]
Which runner should I be using?  There are 4.

EDIT:  I see that the report is being generated, and I used the latest commit, it is also generating the report.  What is the issue?

**Comment by salunkhe-ravi** [comment]
src/test/java/runners/MainRunnerTest.java

Executing the project by RunAs Maven test...

**Comment by salunkhe-ravi** [comment]
I'm unable to get snapshots embedded into the report...that's the issue!

**Comment by anshooarora** [comment]
Please use the below `extent.properties` and look under `test-output/Selenix-Spark/` for the report:

```
extent.reporter.html.start=false
extent.reporter.logger.start=false
extent.reporter.spark.start=true

extent.reporter.html.config=src/test/resources/extent-config.xml
extent.reporter.logger.config=src/test/resources/extent-config.xml
extent.reporter.spark.config=src/test/resources/extent-config.xml

extent.reporter.html.out=test-output/Selenix-HtmlReport/SelenixHtmlReport.html
extent.reporter.logger.out=test-output/Selenix-Logger
extent.reporter.spark.out=test-output/Selenix-Spark/

screesnshot.dir=test-output/
screenshot.rel.path=../
```

HtmlReporter has been deprecated as there are certain features it does not support.  Spark is the default version 4 reporter and it supports attaching screenshots on all test/step levels.  It will create a single file just like the HtmlReporter.

**Comment by salunkhe-ravi** [comment]
You are a genius @anshooarora . 

Thanks a ton for all your help & support! 
Billiant!

Issue resolved! :)

Updated my repo for everyones reference.

https://github.com/salunkhe-ravi/Selenix

Also, can we get the final release version of this snapshot on mvn?.

And any plans for Cucumber v5?

**Comment by anshooarora** [comment]
Mounish of grasshopper.tech has created the version 5 adapter which "is based on the existing adapter for version 4 but has been modified to work with version 5".

More details here:  https://grasshopper.tech/1697/#comment-874

**Comment by grasshopper7** [comment]
I have uploaded the cucumber5-adapter to Maven. https://mvnrepository.com/artifact/tech.grasshopper/extentreports-cucumber5-adapter.

Give it a try. Thx.

**Comment by salunkhe-ravi** [comment]
Yes sure!
Will play around today and update if anything.


Sent from Yahoo Mail for iPhone


On Monday, March 23, 2020, 11:10 AM, grasshopper <notifications@github.com> wrote:




I have uploaded the cucumber5-adapter to Maven. https://mvnrepository.com/artifact/tech.grasshopper/extentreports-cucumber5-adapter.

Give it a try. Thx.

**Comment by abhishekrhyme** [comment]
<img width="1149" alt="Screen Shot 2020-04-08 at 1 34 05 AM" src="https://user-images.githubusercontent.com/62941664/78714294-4242eb00-7939-11ea-904c-30456787635d.png">

I am not getting screenshot in spark report.
using adapter 1.0.8 and cucumber 4.8.1 
also, 1.0.11-SNAPSHOT repo not available.

**Comment by salunkhe-ravi** [comment]
Please take a look at my repository and go use the pom.xml
Thanks And Regards, Ravi Salunkhe.+91 9892 033 961https://www.linkedin.com/in/ravi-salunkhe-15485539/ 

    On Wednesday, 8 April, 2020, 01:37:28 am IST, abhishekrhyme <notifications@github.com> wrote:  
 
 




I am not getting screenshot in spark report.
using adapter 1.0.8 and cucumber 4.8.1
also, 1.0.11-SNAPSHOT repo not available.

**Comment by abhishekrhyme** [comment]
Dude your Pom is outdated, some of snapshots don’t even exist now, please verify before giving suggestion

**Comment by abhishekrhyme** [comment]
![D92475C6-81DB-4692-B988-AA60379F9C86](https://user-images.githubusercontent.com/62941664/79022058-c051fc80-7b9a-11ea-8937-870fc9239989.png)

Check this it does not exist anymore 

@salunkhe-ravi

**Comment by anshooarora** [comment]
The SNAPSHOT release exists.  Have you enabled SNAPSHOTS from your m2/settings.xml?  Anyhow, the release version is now available so I would suggest using that.  

Note:  currently, `@Before` and `@After` are working, but `@BeforeStep` and `@AfterStep` aren't.  This will be fixed in the upcoming version 1.0.12 release,  fix available with `1.0.12-SNAPSHOT`.

**Comment by salunkhe-ravi** [comment]
Let know if that worked for you and share your fix with others for them to update.
Hope you were aware of the settings.xml?!


Sent from Yahoo Mail for iPhone


On Saturday, April 11, 2020, 2:25 AM, Anshoo Arora <notifications@github.com> wrote:




The SNAPSHOT release exists. Have you enabled SNAPSHOTS from your m2/settings.xml? Anyhow, the release version is now available so I would suggest using that.

Note: currently, @Before and @After are working, but @BeforeStep and @AfterStep aren't. This will be fixed in the upcoming version 1.0.12 release, fix available with 1.0.12-SNAPSHOT.

**Comment by surajgupta7175** [comment]
> Dude your Pom is outdated, some of snapshots don’t even exist now, please verify before giving suggestion

@abhishekrhyme Somebody trying to help DUDE!!
He doesn't know about SNAPSHOTS I am sure. He even didn't try to research which was the latest version back then and commenting outdated.

**Comment by shahnawazm786** [comment]
Scenario: Logo presence on orangeHRM home page # src/test/resources/features/Test.feature:2
Open the amazon browserLogo presence on orangeHRM home pagefile:///F:/MavenProject/src/test/resources/features/Test.feature:2Hello
  Given I launch chrome browser                # stepDefinitions.OrangehrmSteps.i_launch_chrome_browser()
      java.lang.NullPointerException
	at Hooks.HooksClass.capture(HooksClass.java:27)

  When I open orange hrm homepage              # stepDefinitions.OrangehrmSteps.i_open_orange_hrm_homepage()
  Then I verify that the logo present on page  # stepDefinitions.OrangehrmSteps.i_verify_that_the_logo_present_on_page()
  And close browser                            # stepDefinitions.OrangehrmSteps.close_browser()
Close the browserLogo presence on orangeHRM home pagefile:///F:/MavenProject/src/test/resources/features/Test.feature:2
java.lang.NullPointerException
	at Hooks.HooksClass.capture(HooksClass.java:27)

It is not captured
