### ISSUE TITLE
Scenario outline is showing as 2 separate scenarios in the Dashboard

### ISSUE THREAD

**Issue by jbnzdev** [extent-framework/extentreports-cucumber4-adapter#30]
When running a Scenario outline with 2 examples, the number of scenarios is displayed as 3.
This is because the parent Scenario as one, and 2 when the scenario is run 2 times based on the examples.

![image](https://user-images.githubusercontent.com/32446985/65317467-cbf4bc00-db93-11e9-9650-24455bc33655.png)

The mismatch in the scenario count is visible the above mentioned screenshot.

**Comment by jbnzdev** [comment]
Hi @anshooarora , Is there any update on the above mentioned issue. ?

**Comment by anshooarora** [comment]
@jeybn Looking into this, please bare with me as I look into this along with several other open tickets/questions and issues.

**Comment by anshooarora** [comment]
This has been fixed in #50.

**Comment by bughunter7** [comment]
Hi @anshooarora  its the same issue I am still facing using extent report cucumber 6 adapter .
Dependency used - 

                    <dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extentreports-cucumber6-adapter</artifactId>
			<version>1.2.0</version>
			<scope>test</scope>
		</dependency>

While Using Scenario outline it shows incorrect results please check and let me know the solution .

[
![scnissue](https://user-images.githubusercontent.com/55976995/96224221-d9ee5980-0fac-11eb-95e8-f647ad46d6b2.PNG)
![sc2](https://user-images.githubusercontent.com/55976995/96224551-6d278f00-0fad-11eb-93fe-5d74ec02903b.PNG)

](url)

**Comment by Savph** [comment]
Hi @anshooarora , I'm also facing same above mentioned issue using extent report cucumber 7 adapter . Could you please help resolve this.

Though I have run only **1 scenario** in Tags table it is showing as **2 Passed**

![image](https://user-images.githubusercontent.com/115139133/194236386-8014c8a2-0b27-423f-a45c-795e77a9688f.png)

Dependencies used
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>5.0.9</version>
</dependency>


<dependency>
    <groupId>tech.grasshopper</groupId>
    <artifactId>extentreports-cucumber7-adapter</artifactId>
    <version>1.7.0</version>
</dependency>

<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>7.8.1</version>
</dependency>

**Comment by SriNandinigj** [comment]
Even I'm facing the same issue with example section used. What is the solution for this issue? @anshooarora
